INSERT INTO cliente (nombre,apellidouno,apellidodos,email) VALUES ("Ibrahim","Rantoul","Galbraeth","igalbraeth0@vistaprint.com"),
            ("Rowe","Martschik","Kember","rkember1@ca.gov"),
            ("Krystalle","Iacavone","Falvey","kfalvey2@cdc.gov"),
            ("Nolan","Ansell","Roux","nroux3@jalbum.net"),
            ("Rainer","Massimo","Posselow","rposselow4@altervista.org"),
            ("Lorrayne","Lain","Lawrie","llawrie5@virginia.edu"),
            ("Edin","Roff","De Cleyne","edecleyne6@netvibes.com"),
            ("Nicolette","Element","Tidy","ntidy7@fema.gov"),
            ("Elli","McCathay","Scoggans","escoggans8@i2i.jp"),
            ("Eduardo","Fisbey","Halt","ehalt9@clickbank.net"),
            ("Petra","Mabe","Knevit","pknevita@myspace.com"),
            ("Juanita","Sparrowe","Shimmin","jshimminb@mlb.com"),
            ("Brian","Rikel","Elgar","belgarc@php.net"),
            ("Shep","Balloch","Shewen","sshewend@goo.ne.jp"),
            ("Manda","Yewman","Swalteridge","mswalteridgee@seattletimes.com"),
            ("Nap","Docwra","Lyddyard","nlyddyardf@omniture.com"),
            ("Darb","Phelipeau","Bartelot","dbartelotg@aboutads.info"),
            ("Mallory","Caslin","Roblin","mroblinh@cornell.edu"),
            ("Blythe","Ruscoe","Shakle","bshaklei@thetimes.co.uk"),
            ("Lanni","Richardsson","McCamish","lmccamishj@ox.ac.uk");
            
            INSERT INTO coche (modelo,precio,fabricante,anio,km) VALUES ("Clio",14000,"Renault",2006,200000),
            ("Astra",13000,"Opel",2022,3000),
            ("Megane",17000,"Renault",2014,3000),
            ("Insignia",1500,"Opel",2006,30000),
            ("Traffic",22000,"Renault",2022,1000),
            ("Vivaro",22000,"Opel",2023,0),
            ("tucson",14000,"hyundai",20021,4000),
            ("xc40",14000,"Volvo",20020,50000),
            ("kona",7000,"hyundai",20010,2000),
            ("xc60",17000,"Volvo",20022,0),
            ("bayon",2000,"hyundai",2008,350000);
            
            INSERT INTO ventas (id_cliente,id_coche,anio_de_compra) VALUES (1,3,2017),
            (7,6,2020),
            (9,2,2015),
            (15,8,2022),
            (7,7,2021);